"""update_schema_phase_1

Revision ID: 5eb32febd008
Revises: 74c9255a2428
Create Date: 2026-08-16 13:39:01.202920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eb32febd008'
down_revision: Union[str, None] = '74c9255a2428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_logs', 'pii_detected',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.add_column('tickets', sa.Column('is_escalated', sa.Boolean(), nullable=True))
    op.alter_column('tickets', 'category_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'category_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_column('tickets', 'is_escalated')
    op.alter_column('ai_logs', 'pii_detected',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
